name: MobPreventer
version: 1.0.5
main: me.tofpu.mobpreventer.MobPreventer
api-version: 1.16
authors: [Tofpu]
description: A customizeable plugin which its purpose is to prevent certain mobs from spawning.
commands:
  mobpreventer:
    description: a command!
